src/Musical/Entity/Review/Collection.php
<?php
/**
 * Created by \diModelsManager
 * Date: 12.04.2021
 * Time: 18:31
 */

namespace Musical\Entity\Review;

use Musical\Traits\Collection\OldIdInside;

/**
 * Class Collection
 * Methods list for IDE
 *
 * @method $this filterByType($value, $operator = null)
 * @method $this filterByEmail($value, $operator = null)
 * @method $this filterByPosition($value, $operator = null)
 * @method $this filterByEnPosition($value, $operator = null)
 *
 * @method $this orderByType($direction = null)
 * @method $this orderByEmail($direction = null)
 * @method $this orderByPosition($direction = null)
 * @method $this orderByEnPosition($direction = null)
 *
 * @method $this selectType()
 * @method $this selectEmail()
 * @method $this selectPosition()
 * @method $this selectEnPosition()
 *
 * @method $this filterByLocalizedPosition($value, $operator = null)
 *
 * @method $this orderByLocalizedPosition($direction = null)
 *
 * @method $this selectLocalizedPosition()
 */
class Collection extends \Musical\Entity\BaseEntity\Collection
{
    use OldIdInside;

    const type = \diTypes::review;
	const connection_name = 'default';
    protected $table = 'review';
    protected $modelType = 'review';
}

src/Musical/Entity/Review/Model.php
<?php
/**
 * Created by \diModelsManager
 * Date: 12.04.2021
 * Time: 18:31
 */

namespace Musical\Entity\Review;

use diCore\Base\CMS;
use diCore\Database\FieldType;
use Musical\Traits\Model\OldIdInside;

/**
 * Class Model
 * Methods list for IDE
 *
 * @method integer	getType
 * @method string	getEmail
 * @method string	getPosition
 * @method string	getEnPosition
 *
 * @method bool hasType
 * @method bool hasEmail
 * @method bool hasPosition
 * @method bool hasEnPosition
 *
 * @method $this setType($value)
 * @method $this setEmail($value)
 * @method $this setPosition($value)
 * @method $this setEnPosition($value)
 *
 * @method string	localizedPosition
 */
class Model extends \Musical\Entity\BaseEntity\Model
{
    use OldIdInside;

    const type = \diTypes::review;
	const connection_name = 'default';
    const table = 'review';
    protected $table = 'review';
	const slug_field_name = self::SLUG_FIELD_NAME;
    protected $localizedFields = ['slug', 'slug_source', 'title', 'position', 'short_content', 'content', 'meta_title', 'meta_keywords', 'meta_description', 'visible'];

	protected static $fieldTypes = [
        'id' => FieldType::int,
        'type' => FieldType::int,
        'email' => FieldType::string,
        'slug' => FieldType::string,
        'slug_source' => FieldType::string,
        'title' => FieldType::string,
        'meta_title' => FieldType::string,
        'meta_keywords' => FieldType::string,
        'meta_description' => FieldType::string,
        'position' => FieldType::string,
        'short_content' => FieldType::string,
        'content' => FieldType::string,
        'visible' => FieldType::int,
        'en_slug' => FieldType::string,
        'en_slug_source' => FieldType::string,
        'en_title' => FieldType::string,
        'en_position' => FieldType::string,
        'en_short_content' => FieldType::string,
        'en_content' => FieldType::string,
        'en_meta_title' => FieldType::string,
        'en_meta_keywords' => FieldType::string,
        'en_meta_description' => FieldType::string,
        'en_visible' => FieldType::int,
        'pic' => FieldType::string,
        'pic_w' => FieldType::int,
        'pic_h' => FieldType::int,
        'created_at' => FieldType::timestamp,
        'order_num' => FieldType::int,
    ];

    const TYPE_GENERAL = 1;
    const TYPE_CELEBRITY = 2;

    public static $types = [
        self::TYPE_GENERAL => 'Зрителей',
        self::TYPE_CELEBRITY => 'Звезд',
    ];

    public function getHref()
    {
        return $this->__getPrefixForHref() . '/' . CMS::ct('reviews') . '/#' . $this->getSlug();
    }

    public function isGeneral()
    {
        return $this->getType() == static::TYPE_GENERAL;
    }

    public function isCelebrity()
    {
        return $this->getType() == static::TYPE_CELEBRITY;
    }

    public function getTypeTitle()
    {
        return static::$types[$this->getType()] ?? null;
    }

    public function validate()
    {
        if (!$this->hasTitle()) {
            $this->addValidationError('Введите ФИО', 'title');
        }

        if (!$this->hasContent()) {
            $this->addValidationError('Введите текст отзыва', 'content');
        }

        if ($this->hasEmail() && !\diEmail::isValid($this->getEmail())) {
            $this->addValidationError('Введите корректный email', 'email');
        }

        return $this;
    }
}

templates/reviews/page.html.twig
{% include '_parts/h1.html.twig' %}

<div class="send_reviews">
    <a class="link js-show_modal" href="#modal_reviews_form">{{ local['review.add'] }}</a>
</div>

<ul class="list ibs opisanie_list_2 js-tabs">
    <li class="item"><a class="link active" href="#tab_2" data-type="2">{{ local['review.type.of.celebrity'] }}</a></li>
    <li class="item"><a class="link" href="#tab_1" data-type="1">{{ local['review.type.of.general'] }}</a></li>
</ul>

<div id="tab_2" class="reviews" data-type="2">
    <ul class="list ibs reviews_list">
        {% for r in reviews|filter(r => r.isCelebrity()) %}
            {% include 'reviews/row.html.twig' with {
                first: loop.index == 1
            } %}
        {% endfor %}
    </ul>
</div>

<div id="tab_1" class="reviews hidden" data-type="1">
    <ul class="list ibs reviews_list reviews_list_audience">
        {% for r in reviews|filter(r => r.isGeneral()) %}
            {% include 'reviews/row.html.twig' with {
                first: loop.index == 1
            } %}
        {% endfor %}
    </ul>
</div>

templates/reviews/row.html.twig
<li class="item" data-type="{{ r['type'] }}">
    <a class="link js-show_modal" data-modal-class="modal_reviews_block" href="#modal-review-{{ r['id'] }}">
        {% set name_class = r.isCelebrity() ? 'name' : 'name_beige' %}
        {% set read_class = first and r.isGeneral() ? 'btn btn_2' : 'btn btn_2' %}
        {% if r.isCelebrity() %}
            <div class="fig">
                <img class="img" src="{{ r['pic_with_path'] }}" alt="{{ r['localized_title'] }} {{ r['localized_position'] }}" loading="lazy">
            </div>
        {% endif %}
        <div class="{{ name_class }}">{{ r['localized_title'] }}</div>
        {% if r.isCelebrity() %}
            <div class="post">{{ r['localized_position'] }}</div>
        {% endif %}
        <div class="text">{{ r['localized_short_content'] }}</div>
        <div class="{{ read_class }}">{{ local['review.read'] }}</div>
    </a>
    <template id="modal-review-{{ r['id'] }}">
        {% if r.isCelebrity() %}
            <div class="fig">
                <img class="img" src="{{ r['pic_with_path'] }}" alt="{{ r['localized_title'] }} {{ r['localized_position'] }}" loading="lazy">
            </div>
        {% endif %}
        <div class="name">{{ r['localized_title'] }}</div>
        {% if r.isCelebrity() %}
            <div class="post">{{ r['localized_position'] }}</div>
        {% endif %}
        <div class="text">{{ r['localized_content']|raw ?: r['content'] }}</div>
    </template>
</li>